FROM python:3.12-slim-bookworm
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install -r requirements.txt --no-cache-dir
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000"]